server:
  port: 8910
  error:
    whitelabel:
      enabled: false

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://localhost:5432/food_users_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  flyway:
    flyway:
      enabled: true
      locations: classpath:db/migration
      baseline-on-migrate: true
      baseline-version: 1
      schemas: public
      validate-on-migrate: true
      clean-on-validation-error: false
      out-of-order: false
      table: flyway_schema_history
  mvc:
    throw-exception-if-no-handler-found: true
    servlet:
      path: /

jwt:
  secret: hits2025972303hits2025972303hits20259723032025hits
  lifetime: 30m
  refresh-lifetime: 14400m

url:
  order-service-url: http://order-service:8096

features:
  enableSaveEditedUser: ${ENABLE_SAVE_EDITED_USER:true}
  enableBadStatusInsteadSuccess: ${ENABLE_BAD_STATUS_INSTEAD_OF_SUCCESS:false}
  enableChangePassword: ${ENABLE_CHANGE_PASSWORD:true}
  enableStaffAuthViaPhoneNumber: ${ENABLE_STAFF_AUTH_VIA_PHONE_NUMBER:false}
  enableRefreshSession: ${ENABLE_REFRESH_SESSION:true}
  enableInternalServerError: ${ENABLE_INTERNAL_SERVER_ERROR:false}
  enableSaveNullableProperties: ${ENABLE_SAVE_NULLABLE_PROPS:false}
  enableReturnEmptyResult: ${ENABLE_RETURN_EMPTY_RESULT:false}
  enableMixedUpTokens: ${ENABLE_MIXED_UP_TOKENS:false}
  enableExpiredAccessToken: ${ENABLE_EXPIRED_ACCESS_TOKEN:false}

logging:
  level:
    org.springframework.security: trace
    org.apache.http: DEBUG