server:
  port: 8100

spring:
  application:
    name: log-service
  datasource:
    url: jdbc:postgresql://localhost:5436/files_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  mvc:
    throw-exception-if-no-handler-found: true
    servlet:
      path: /
  file:
    saving-dir: ./files

logging:
  level:
    org.springframework.security: trace
    org.apache.http: DEBUG
    com.netflix.discovery: OFF
    org.springframework.cloud.netflix.eureka: OFF
    org.springframework.cloud.netflix.eureka.server: OFF
    com.netflix.eureka: OFF

settings:
  strategy: LOCAL
