server:
  port: 8096

spring:
  application:
    name: order-service
  datasource:
#    url: jdbc:postgresql://localhost:5432/mydatabase
    url: jdbc:postgresql://order_db:5432/mydatabase
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 1
    schemas: public
    validate-on-migrate: true
    clean-on-validation-error: false
    out-of-order: false
    table: flyway_schema_history
logging:
  level:
    org.springframework.security: trace

url:
#  user-service-url: http://localhost:8910
#  menu-service-url: http://localhost:8080
  user-service-url: http://user-service:8910
  menu-service-url: http://menu-service:8080

feature:
  bugWrongStatisticCounter: false
  bugWrongOrderNumberCounter: false
  bugWrongStatusChange: false
  bugOperatorWithoutFullName: false
  bugStatusHistoryNotChanges: false
  bugInvalidPriceCountAfterDishAddInOrder: false
  bugInvalidPriceCountAfterDishDeleteFromOrder: false
  bugCantGetDishInformation: false
  bugErrorStatusChangeWhenDeclineOrder: false
  bugNotIncreaseDishAmountAfterAdd: false
jwt:
  secret: hits2025972303hits2025972303hits20259723032025hits
  lifetime: 30m